name: 'robin-moser/portainer-stack-deploy'
description: 'GitHub Action to deploy and update stacks over the Portainer API'
author: 'robin-moser'
branding:
  icon: 'cloud'
  color: 'green'

inputs:
  portainer-host:
    required: true
    description: 'Portainer host, eg. https://myportainer.instance.com'
  token:
    required: true
    description: 'Token for the Portainer login'
  swarm-id:
    required: false
    description: 'ID of the swarm. Only required if you deploy to a swarm.'
  endpoint-id:
    required: false
    default: '1'
    description: 'ID of the endpoint to deploy the stack to. When specified, only stacks within this endpoint will be considered for updates.'
  stack-name:
    required: true
    description: 'Name for the Portainer stack'
  stack-definition:
    required: false
    description: 'The path to the docker-compose stack stack definition file, eg. stack-definition.yml'
  template-variables:
    required: false
    description: 'If given, these variables will be replaced in docker-compose file by handlebars'
  tag-replacements:
    required: false
    description: 'Multiline string of image:tag combinations, each occurence of "image" will be deployed with the new "tag"'

runs:
  using: 'node12'
  main: 'dist/index.js'
